server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devcollab}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:devcollab123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

app.jwt.secret=devcollab_super_secret_key_change_this_in_production_2026
app.jwt.expiration=86400000
app.gemini.api-key=${GEMINI_API_KEY:}
app.gemini.model=${GEMINI_MODEL:gemini-2.0-flash}
